### ISSUE TITLE
H3 implementation

### ISSUE THREAD

**Issue by stammw** [djc/quinn#362]
This a tracking issue for the H3 implementation.

- [ ] [H3: make the FrameStream buffer growable](#354)
- [ ] [H3: body buffer size configuration](#355)
- [ ] [H3: Streaming mode for receiving body](#356)
- [ ] [H3: Streaming mode for sending body](#357)
- [ ] [H3: Control stream implementation](#358)
- [ ] [ QPACK: receive two ack for one stream](#359)
- [ ] [H3: stateful QPACK encoding](#360)
- [ ] [H3: Push streams](#361)

**Comment by ookhoi** [comment]
Do we know of a site that supports http/3 so we can test this implementation? My duckduckgo-foo is failing me apparently.

**Comment by Ralith** [comment]
Most other QUIC implementers host public HTTP/3 endpoints for interop testing purposes; they can be found in the QUIC implementers' slack.

**Comment by djc** [comment]
Or have a look at https://github.com/quicwg/base-drafts/wiki/Implementations and find some public servers that have a H3 ALPN token

**Comment by djc** [comment]
Also https://mobile.twitter.com/netray_io/status/1138354237182795776
