### ISSUE TITLE
H3: Update to draft-28

### ISSUE THREAD

**Issue by stammw** [djc/quinn#785]
- [ ] Draft version in `Alt-Svc` could be the cause of incompatibility of some clients. The draft shows something like `Alt-Svc: h3=":50781"`
- [ ] Check authority based on CN field of the certificate subject or  dNSName, iPAddress in the subjectAltName field. [#3558](https://github.com/quicwg/base-drafts/pull/3558/files)
- [ ] GoAway from client: [#3129](https://github.com/quicwg/base-drafts/pull/3129/files)
- [ ] Make it mandatory for requests to have either `:authority` or `Host` fields [#3475](https://github.com/quicwg/base-drafts/pull/3475/files)
